"""fixing foreign key

Revision ID: 30fdc08bb5c4
Revises: c4d7f9729c0f
Create Date: 2023-04-27 12:26:25.656485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fdc08bb5c4'
down_revision = 'c4d7f9729c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('witten_review_id', sa.Integer(), nullable=True),
    sa.Column('review_about_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=225), nullable=False),
    sa.ForeignKeyConstraint(['review_about_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['witten_review_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('tier_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('liked_trucks', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('message', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('owner_operator', sa.String(length=225), nullable=True))
        batch_op.add_column(sa.Column('dispatcher', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dispatcher')
        batch_op.drop_column('owner_operator')
        batch_op.drop_column('message')
        batch_op.drop_column('bio')
        batch_op.drop_column('liked_trucks')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('tier_level')
        batch_op.drop_column('company_name')
        batch_op.drop_column('name')

    op.drop_table('review')
    # ### end Alembic commands ###
