"""empty message

Revision ID: 424d39e81e78
Revises: 496bd7bc89b0
Create Date: 2023-04-27 14:25:46.387568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '424d39e81e78'
down_revision = '496bd7bc89b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('written_review_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('review_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['written_review_id'], ['id'])
        batch_op.drop_column('witten_review_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('witten_review_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_ibfk_2', 'user', ['witten_review_id'], ['id'])
        batch_op.drop_column('written_review_id')

    # ### end Alembic commands ###
