"""empty message

Revision ID: 496bd7bc89b0
Revises: 76aeb9521023
Create Date: 2023-04-27 12:34:45.442048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496bd7bc89b0'
down_revision = '76aeb9521023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
