"""empty message

Revision ID: 76aeb9521023
Revises: 30fdc08bb5c4
Create Date: 2023-04-27 12:33:35.282558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76aeb9521023'
down_revision = '30fdc08bb5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner_operator', sa.Boolean(), nullable=False))
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('liked_trucks',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('bio',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('owner_operator')
        batch_op.drop_column('dispatcher')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('dispatcher', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('owner_operator', mysql.VARCHAR(length=225), nullable=True))
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('liked_trucks',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_owner_operator')

    # ### end Alembic commands ###
