"""Init

Revision ID: e23e482457e2
Revises: c8d9dc6b9272
Create Date: 2023-06-09 14:39:12.834937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23e482457e2'
down_revision = 'c8d9dc6b9272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specific_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=225), nullable=False),
    sa.Column('comment_about_specific_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_about_specific_post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specific_post')
    # ### end Alembic commands ###
